# Generated by Django 2.1.3 on 2018-12-03 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20181203_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_Posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 11, 30, 10, 152068, tzinfo=utc)),
        ),
    ]
