# Generated by Django 2.1.3 on 2018-12-04 04:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20181203_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_Posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 4, 8, 10, 995735, tzinfo=utc)),
        ),
    ]
