# Generated by Django 2.1.3 on 2018-12-04 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20181204_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_Posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 5, 38, 34, 864867, tzinfo=utc)),
        ),
    ]
